/* AUTH */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILIURE = "AUTH_LOGIN_FAILURE";


/* BROWSER */
export const MENU_HOME = "MENU_HOME";
export const MENU_DASHBOARD = "MENU_DASHBOARD";
export const MENU_BAMBOOGROVE = "MENU_BAMBOOGROVE";
export const MENU_REPORTMANAGER = "MENU_REPORTMANAGER";
export const MENU_COUNSELMANAGER = "MENU_COUNSELMANAGER";
